name: find
description: Simple, performant state management for Flutter. 
version: 1.1.1
author: Christian Lewis<ctjl96@gmail.com>
homepage: https://github.com/christiantjl/find

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter